name: Cypress Tests

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name
  pull_request:
    branches:
      - main  # Replace 'main' with your branch name

jobs:
  test:
    runs-on: ubuntu-latest
    name: Cypress Tests with chromium browser
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build custom Docker image
      run: |
        docker build -t cypress-test-browser .
      
    - name: Run Cypress tests
      run: |
        docker run --rm cypress-test-browser npm run cypress:run -b chromium
        
   test:     
    runs-on: ubuntu-latest
    name: Cypress Tests with electron browser
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build custom Docker image
      run: |
        docker build -t cypress-test-browser .
      
    - name: Run Cypress tests
      run: |
        docker run --rm cypress-test-browser npm run cypress:run

