name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build custom Docker image
        run: |
          docker build --platform linux/amd64 -t biswabose1992/cypress-test1-amd64 .
 
      - name: Run Cypress tests
        run: |
          docker run --rm -v $PWD:/tests biswabose1992/cypress-test1-amd64

      - name: List Contents of Directory
        run: ls -l /tests/mochawesome-report


      - name: Save Test Artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-reports
          path: /tests/mochawesome-report/*


