name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Cypress tests
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64,linux/arm64
          push: false  # Change to true if you want to push the Docker image

      - name: Run Cypress tests
        run: |
          docker run --rm \
            -v $(pwd)/cypress:/e2e/cypress \
            -v $(pwd)/cypress.json:/e2e/cypress.json \
            cypress-test-browser
