name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   name: Cypress Tests on docker container
# Cypress Docker image with Chrome v78
# and Firefox v70 pre-installed
   container: cypress/browsers:node12.18.3-chrome87-ff82
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v3
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v5
       with:
         browser: chrome
