name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Install dependencies
        run: |
          npm install mochawesome
          
      - name: Run Cypress tests
        run: |
           docker run --rm -v $PWD:/tests -v ${PWD}/mochawesome-report:/tests/mochawesome-report  biswabose1992/cypress-test-amd64 npm run cypress:run --reporter mochawesome

      - name: Merge Mochawesome reports
        run: |
          sudo npx mochawesome-merge mochawesome-report/*.json > output.json && sudo npx marge output.json

          

      - name: Save Test Artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: mochawesome-report
          path: mochawesome-report


