name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx create --name mybuilder --use
          docker buildx build --platform linux/amd64,linux/arm64 -t cypress-test-browser .
 
      - name: Run Cypress tests
        run: |
          docker run --rm biswabose1992/cypress-test-browser npm run cypress:run

      - name: Save Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: /mochawesome-report



