name: Cypress Tests

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name
  pull_request:
    branches:
      - main  # Replace 'main' with your branch name

jobs:   
  electron:     
    runs-on: ubuntu-latest
    name: Cypress Tests with electron browser
    container:
      image: biswabose1992/cypress-test-browser:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
            
    - name: Run Cypress tests
      run: |
        docker run --rm biswabose1992/cypress-test-browser:latest npm run cypress:run



