name: Cypress Tests

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name
  pull_request:
    branches:
      - main  # Replace 'main' with your branch name

jobs:   
  electron:     
    runs-on: ubuntu-latest
    name: Cypress Tests with electron browser
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build custom Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t cypress-test-browser .  
      
    - name: Run Cypress tests
      run: |
        docker run --rm cypress-test-browser npm run cypress:run

    - name: Save Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: /mochawesome-report



