name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: macos-latest
    container:
      image: docker://ghcr.io/docker/for-mac/apple-m1-preview:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Cypress tests
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t cypress-tests .
          docker run --rm -v ${PWD}:/usr/src/app cypress-tests
