name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Run Cypress tests
        run: |
          docker run --rm biswabose1992/cypress-test-amd64 npm run cypress:run

      - name: Save Test Artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-reports
          path: tests/mochawesome-report



