name: Cypress Tests

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name
  pull_request:
    branches:
      - main  # Replace 'main' with your branch name

jobs:
  chrome:
    runs-on: ubuntu-latest
    env:
      using: 'node20'
      main: 'main.js'
    name: Cypress Tests with chromium browser
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build custom Docker image
      run: |
        docker build -t cypress-test-browser .
      
    - name: Run Cypress tests
      run: |
        docker run --rm cypress-test-browser npm run cypress:run -b chromium
        
  electron:     
    runs-on: ubuntu-latest
    env:
      using: 'node20'
      main: 'main.js'
    name: Cypress Tests with electron browser
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: 20
      
    - name: Build custom Docker image
      run: |
        docker build -t cypress-test-browser .
      
    - name: Run Cypress tests
      run: |
        docker run --rm cypress-test-browser npm run cypress:run

