name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Run Cypress tests
        run: |
          docker run --rm -v /Users/Biswadeep.Bose/workspace/learning/cypressTestAutomationFramework/mochawesome-report:/tests/mochawesome-report  biswabose1992/cypress-test-arm64 npm run cypress:run

      - name: List Contents of Directory
        run: ls -l /cypressTestAutomationFramework/mochawesome-report

      - name: Save Test Artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-reports
          path: /tests/mochawesome-report/*


